### ISSUE TITLE
添加mockjs v1.0以上版本支持的新@变量

### ISSUE THREAD

**Issue by wakazekazuto** [appLhui/mock2easy#1]
新增常用变量如下：
- @cparagraph
- @csentence
- @cword
- @ctitle
- @province
- @city
- @conuty

[官方文档](http://mockjs.com/examples.html)

**Comment by appLhui** [comment]
hello， 不好意思工作忙耽误这么就才给予支持，目前代码我已经开发完毕，你可以在 变量规律里项 填写 @dataImage()，类型选择string类型 就能满足新的这些所有变量的需求，请更新至 `0.0.20` 版本 @wakazekazuto
