### ISSUE TITLE
在浏览器中访问服务器上生成的gitbook

### ISSUE THREAD

**Issue by duanbn** [appLhui/mock2easy#4]
因为mock2easy给整个开发团队使用，并不是只有前端同学本机运行，因此mock2easy是搭建在独立的服务器上的，目前点击gitbook按钮在服务器上会生成gitbook目录，但是通过浏览器无法直接访问，建议gitbook可以直接在浏览器中访问服务器上的gitbook  ：）

**Comment by appLhui** [comment]
已经 将gitbook 生成的静态文件 目录 通过 express 做了代理，通过 ./gitbook  即可访问gitbook的 首页
